# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-12-03 18:24:20
This script is an ArcGIS geoprocessing model converted to Python code.
"""
import arcpy  # Import the ArcPy module, which provides access to ArcGIS geoprocessing tools

def Model():  # Define the main function called "Model"

    # Set the overwrite output option to False
    # This means existing output files will not be automatically overwritten
    arcpy.env.overwriteOutput = False

    # Define the path to the input CSV file containing earthquake statistics
    Earthquake_stats_csv = "C:\\Users\\enoch\\Desktop\\School Work\\GEO 104\\Project\\Earthquake stats .csv"

    # Define the output feature class path in a file geodatabase
    Earthquakestats_Coordinate = "C:\\Users\\enoch\\OneDrive - Canadore College\\GEO 115 FINAL PROJECT\\GEO 115 FINAL PROJECT.gdb\\Earthquakestats_Coordinate"
    # Process: Convert the CSV table to point features
    # This tool creates point features from coordinate data in the input table
    arcpy.defense.CoordinateTableToPoint(
        in_table=Earthquake_stats_csv,  # Input CSV file
        out_feature_class=Earthquakestats_Coordinate,  # Output feature class
        x_or_lon_field="Longitude (°)",  # Field containing longitude values
        in_coordinate_format="DD_2",  # Input coordinate format (Decimal Degrees)
        y_or_lat_field="Latitude (°)"  # Field containing latitude values
    )

if __name__ == '__main__':  # This block ensures the script runs only if executed directly (not imported)
    # Set up the global environment settings using a context manager
    with arcpy.EnvManager(
        scratchWorkspace="C:\\Users\\enoch\\OneDrive - Canadore College\\GEO 115 FINAL PROJECT\\GEO 115 FINAL PROJECT.gdb",
        workspace="C:\\Users\\enoch\\OneDrive - Canadore College\\GEO 115 FINAL PROJECT\\GEO 115 FINAL PROJECT.gdb"
    ):
        Model()  # Call the Model function to execute the geoprocessing tasks
